# Generated by Django 4.1.5 on 2023-01-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslot',
            name='bottom_right',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='carslot',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carslot',
            name='slotId',
            field=models.TextField(default='A1'),
        ),
        migrations.AddField(
            model_name='carslot',
            name='top_left',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
