# Generated by Django 4.1.5 on 2023-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslots', '0002_carslot_bottom_right_carslot_occupied_carslot_slotid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carslot',
            old_name='bottom_right',
            new_name='x1',
        ),
        migrations.RenameField(
            model_name='carslot',
            old_name='top_left',
            new_name='x2',
        ),
        migrations.AddField(
            model_name='carslot',
            name='y1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='carslot',
            name='y2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
