# Generated by Django 4.1.5 on 2023-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslots', '0003_rename_bottom_right_carslot_x1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslot',
            name='x1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carslot',
            name='x2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carslot',
            name='y1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='carslot',
            name='y2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
